export const actions = {
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_STOCK_ACTUAL: "ADD_STOCK_ACTUAL",
  REMOVE_STOCK_ACTUAL: "REMOVE_STOCK_ACTUAL",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  REPLACE_STATE: "REPLACE_STATE",
  ADD_PRICE: "ADD_PRICE",
};
